`((tag "Debian")
  (lang "ja")
  (title "clamav")
  (modify-date 2013 12 21)
  (contents 
   (h4 "コマンド")
   (h5 "定義ファイルの更新。")
   (pre ((class "command"))
	(code "$ freshclam"))
   (h5 "ディレクトリを指定してスキャン。")
   (pre ((class "command"))
	(code "$ clamscan -r -i directory"))))
